### ISSUE TITLE
How to build the project 

### ISSUE THREAD

**Issue by dondon21** [ne0z/DamnVulnerableMicroServices#10]
Hello, 

Can you describe how to build the project please ? 
Can I build it without kubernetes ?

Thanks

**Comment by MagicScorpion** [comment]
yeah, I have the same question.

**Comment by ne0z** [comment]
Hello, very sorry for the late reply. It can run directly without Kubernetes by using docker. Just run ```docker-compose up -d```

**Comment by MagicScorpion** [comment]
@ne0z : this is giving an error 

kali@kali:~/DamnVulnerableMicroServices$ sudo docker-compose up -d
ERROR: Top level object in './docker-compose.yaml' needs to be an object not '<class 'NoneType'>'.
kali@kali:~/DamnVulnerableMicroServices$

**Comment by MagicScorpion** [comment]
@ne0z : this is giving an error

```
kali@kali:~/DamnVulnerableMicroServices$ sudo docker-compose up -d
ERROR: Top level object in './docker-compose.yaml' needs to be an object not '<class 'NoneType'>'.
kali@kali:~/DamnVulnerableMicroServices$ 
```

**Comment by MagicScorpion** [comment]
@ne0z : this is giving error

`kali@kali:~/DamnVulnerableMicroServices$ sudo docker-compose up -d
ERROR: Top level object in './docker-compose.yaml' needs to be an object not '<class 'NoneType'>'.
kali@kali:~/DamnVulnerableMicroServices$ 
`

**Comment by MagicScorpion** [comment]
@ne0z Hey Danang any updates on this?

**Comment by ne0z** [comment]
Hi all, very sorry for the late reply. I will update complete documentation on how to run this project tomorrow. Just want to make clear this project is under development. I mean this project is not complete yet. But I am happy if you all can help me to continue this project.

**Comment by ne0z** [comment]
Hei there, I have been updated the documentation.
